src/runtime.rs
While creating docker image for CI, I found that it is necessary to have SSL certs installed for running tests. It looks like this behavior can be avoided by adding one more option to cargo.
With this change it won't be necessary to have internet connection in order to run tests.
=> Avoid downloading metadata for all dependencies

cargo-insta/src/inline.rs
The InLine FilePatcher wasn't finding the correct snapshot (or even finding it at all) after a previous "skip". 
I don't think the line number check is sufficient. 
If you want some unit tests: try mine  https://bitbucket.org/athaliana/typescript-definitions/src/master/tests/typescript.rs
=> fixing search for Inline snapshot after a skip.

cargo-insta/src/cli.rs
We don't actually accept on uppercase `A`!
=> Use lowercase `a` when priting accept message

src/lib.rs, src/macros.rs, src/serialization.rs, tests/test_inline.rs
Closes #22 
The primary change was to introduce a new `SnapshotLocation` enum; it's intended to track where a snapshot is being stored – inline vs in a `.snap` file. I updated the various macro calls to just use it as a third parameter to `serialize_value` / `serialize_value_redacted`, which seemed simplest to me.
The new behavior is as follows:
> If a YAML snapshot is inline, we don't trim the leading `---\n`; in all other cases, we maintain the existing behavior.
=> Retain YAML --- header in inline YAML snapshots

cargo-insta/src/cargo.rs, cargo-insta/src/cli.rs, cargo-insta/src/inline.rs, src/runtime.rs, tests/test_inline.rs
This fixes #28
Not happy with the choice of character yet (`│`) which seems to have some bad drawing artifacts in vscode.
=> Improve indentation of inline snapshots

tests/snapshots/test_basic__debug_vector.snap, tests/snapshots/test_basic__unnamed_debug_vector-2.snap, tests/snapshots/test_basic__unnamed_debug_vector-3.snap, tests/snapshots/test_basic__unnamed_debug_vector.snap, tests/snapshots/test_redaction__foo_bar.snap, tests/snapshots/test_redaction__foo_bar_alt.snap, tests/snapshots/test_redaction__foo_bar_full_range.snap, tests/snapshots/test_redaction__foo_bar_range.snap, tests/snapshots/test_redaction__foo_bar_range_from.snap, tests/snapshots/test_redaction__foo_bar_range_to.snap, tests/test_inline.rs
Edit: removed as changed focus of PR
<details>
...this is hidden, collapsable content...
Not sure why this didn't work:
```patch
diff --git src/runtime.rs src/runtime.rs
index bdb4d82..9281798 100644
--- src/runtime.rs
+++ src/runtime.rs
@@ -555,6 +555,7 @@ pub fn assert_snapshot(
}
if should_fail_in_tests() {
+        #[allow(clippy::assertions_on_constants)]
assert!(
false,
"snapshot assertion for '{}' failed in line {}",
```
</details>
Any there any good first issues for those looking for some rust exposure and interested in expect tests?
=> Rust 1.35 format changes

Cargo.toml, src/macros.rs, tests/snapshots/test_inline__unnamed_single_line-2.snap, tests/snapshots/test_inline__unnamed_single_line.snap, tests/test_inline.rs
While looking into https://github.com/mitsuhiko/insta/issues/36, I 'cleaned up' this macro, along the margin.
Let me know if I missing anything
=> Allow unnamed snapshots to compile

Makefile, src/runtime.rs
This doesn't solve the issue I was looking at, but it hopefully cleans up a function and adds some tests.
There's still a unicode issue somewhere else in the code which means replacing inline code where one of the characters is unicode doesn't work well
Let me know any feedback / preferences around tests. Also possible [I'm missing the reason](https://en.wikipedia.org/wiki/Wikipedia:Chesterton%27s_fence) behind the original code
=> Simplify & test format_rust_expression

src/runtime.rs, tests/snapshots/test_inline__something-2.snap, tests/snapshots/test_inline__something.snap, tests/test_inline.rs
**Summary:**
Fix getting thread names by aligning it with module path
name extraction: only get the last `::` part.
**BREAKING:** This change is incompatible with past snapshots.
**Test plan:**
Added new snapshot tests with threads. Confirmed they
fail when the fix is reverted.
=> fix(thread): Fix thread naming for snapshots

cargo-insta/src/inline.rs, src/lib.rs, src/runtime.rs, src/snapshot.rs
Encapsulates:
- Reading from inline values
- Writing out to inline values with an indentation
- `PartialEq`, which previously was implemented inline
- Hopefully some others in the future
Somewhat overlapping with https://github.com/mitsuhiko/insta/pull/52; I tried to implement separately as this has no API impact. This can be merged first.
It's not a perfect API - there's now another method `Snapshot.contents_str` to get a `&str` directly - and I generally find adding types over primitives adds cruft
Open to any feedback / suggestions as ever
=> Encapsulate operations on Snapshot values into a struct SnapshotContents

cargo-insta/src/cargo.rs, src/runtime.rs, src/snapshot.rs
This deletes stale pending snapshots after tests as good as possible.
=> If tests pass, clear out pending snapshots

src/legacy_macros.rs
I think with all the changes we missed `assert_serialized_snapshot_matches`
=> missing assert_serialized_snapshot_matches

src/content.rs
`Content::walk` claims to be recursive, but actually isn't! This caused the `sort_maps` feature to only affect maps at the top level, which is causing snapshot nondeterminism in one of my projects.
Additionally, three tuple-related variants were not present. I don't think I had these present in my projects, but it seems they were omitted by error.
I changed `walk` to accept the `visit` callback via a reference instead of by value like before, since now that reference needs to be passed through multiple calls to `Self::walk` and cannot be moved.
=> Fix Content::walk not being recursive

Cargo.toml
Bump console to 0.9.0 to remove dependencies on crates that depend on insta.
=> console 0.9.0

cargo-insta/Cargo.toml
=> Bump console to 0.9.0 in cargo-insta

src/runtime.rs
Clippy complained that there was an identity conversion. The function
`path_to_storage` returns a `String`. The call to `replace` inside
the `path_to_storage` function returns a `String`. That means the call
to `into` is not needed because the type is already a `String`.
=> Remove identity conversion

README.md
This adds the correct syntax highlighting to the markdown snippets in the readme
=> fix syntax highlighting in readme

src/runtime.rs, src/snapshots/insta__test__embedded.snap, src/snapshots/test__embedded.snap, tests/snapshots/test_basic__nested__nested_module.snap, tests/test_basic.rs
Closes https://github.com/mitsuhiko/insta/issues/78
Is this the right design? A good case is the `insta__test__embedded.snap` change below. I suspect those cases are rare; though it's a breaking change where they do exist.
I need to adds a whatsnew
=> Use full module path for test names

Cargo.toml, Makefile, README.md, src/lib.rs, src/runtime.rs
In some situations rust-test does not set a thread name when it runs tests
which causes snapshots to be named "main".  This is a pretty bad behavior
because it means that depending on how you run the tests the snapshot names
will be different.
This now adds a new feature `backtrace`.  There we will try to recover
the test name from the call stack.
This is not ideal.  Ideally there was an API to determine the test name
from an API.
This fixes #94
=> Add support for test name recovery from the call stack

Cargo.toml, README.md, src/glob.rs, src/lib.rs, src/macros.rs, src/runtime.rs, src/settings.rs, src/snapshot.rs, tests/inputs/hello.txt, tests/snapshots/test_suffixes__basic_globbing@hello.txt.snap, tests/snapshots/test_suffixes__basic_suffixes@1.snap, tests/snapshots/test_suffixes__basic_suffixes@2.snap, tests/snapshots/test_suffixes__basic_suffixes@3.snap, tests/test_suffixes.rs
This is another attempt of implementing globbing. Replaces #109
The motivation here is that the glob support is just a thin wrapper around an expanded snapshot naming system. You can now set suffixes for snapshot names and reference files for the meta data independent of the `glob!` macro so users can use something other than globbing if wanted.
=> Add glob support

src/lib.rs, src/macros.rs, src/runtime.rs
Uses the already existing infrastructure to find the cargo manifest directory. Fixes #119.
=> Fix insta::glob! in workspaces

Cargo.toml, cargo-insta/Cargo.toml
=> Chore: bump deps

Cargo.toml, src/lib.rs, src/macros.rs, src/serialization.rs, tests/snapshots/test_redaction__user_csv.snap, tests/test_inline.rs, tests/test_redaction.rs
Hey! Thanks for the amazing library.
I needed to be able to perform redactions on CSV representations of serialized objects, so added an `assert_csv_snapshot` macro.
The PR follows the rest of the repo wrt to the `csv` dependency and associated macro being optional.
=> Add CSV support

cargo-insta/src/main.rs, src/lib.rs, src/macros.rs, src/settings.rs
This does two main things:
- For code blocks that are not Rust code, use ```` ```text```` rather than ```` ```ignore````
- For code blocks that are Rust code, use ```` ```no_run```` and not ```` ```ignore````, and make them compile so doc tests check they continue to compile
=> Check more doc code blocks

src/macros.rs
It looks like this docstring was intended to refer to the _yaml_ macro rather than a self-reference to the _toml_ version.
=> fix reference to "assert_yaml_snapshot" in "assert_toml_snapshot" docs

CHANGELOG.md, src/glob.rs, src/settings.rs, tests/snapshots/test_glob__basic_globbing@goodbye.txt.snap, tests/snapshots/test_glob__basic_globbing@hello.txt.snap, tests/snapshots/test_glob__globs_follow_links@goodbye.txt.snap, tests/snapshots/test_glob__globs_follow_links@hello.txt.snap, tests/test_glob.rs
There was a regression that broke glob not working correctly. This now also changes it so that empty globs fail by default.
Fixes #151.
=> Fix glob not working and fail if it does not return matches

CHANGELOG.md, src/serialization.rs, tests/test_inline.rs
This changes the CSV serialization format to support multiple values toplevel.
This is technically a breaking change but because the existing format is so useless I think it's fair to assume that nobody would be using this feature in the current form.
Fixes #156
=> Change CSV serialization format to support multiple values

Cargo.toml, cargo-insta/Cargo.lock, src/runtime.rs
I will bump this further to 1.3.0 after making similar compatible with older rust versions. See #161
=> Update similar to 1.2.0 and enable inline highlighting

src/runtime.rs, tests/test_inline.rs
Insta could end up producing bad inline snapshots when empty lines were involved.
Refs #117
=> Fix empty lines confusing inline snapshots

CHANGELOG.md, src/content.rs, tests/test_basic.rs
This unconditionally adds support for i128/u128 as we're only supporting rustc versions where it is available.
Fixes #167
=> Added i128/u128 support

CHANGELOG.md, src/runtime.rs, src/snapshot.rs, tests/snapshots/test_bugs__crlf.snap, tests/snapshots/test_bugs__trailing_crlf.snap, tests/test_bugs.rs
Before if you used windows newlines instead of unix newlines snapshots would always
mismatch because they were inconsistently normalized.
Fixes #171
=> Normalize newlines before comparision

src/runtime.rs
Ends up spamming the test log quite a bit
=> chore: Remove dbg! printing

cargo-insta/src/cli.rs
This PR allows passing arguments to cargo test when `cargo insta test` is run, by doing passing arguments after a `--`
e.g. `cargo insta test -- --test test_name`
Closes #182 
Other options which were normally forwarded to cargo test such as `cargo insta test --release` or `cargo insta test --features feature_name` were left for backwards compatibility. They should probably be deprecated in favour of `cargo insta test -- --release` etc., not sure if you want to put a message as such or just leave it?
=> Allow passing options to cargo test

CHANGELOG.md, src/redaction.rs, src/select_grammar.pest, tests/snapshots/test_redaction__map_key_redaction.snap, tests/test_redaction.rs
This adds the ability to redact keys in collections by using the special `$key` field.
Fixes #192
=> Added the ability to redact collection keys

README.md
The old link pointed to a now deleted section in the Readme. New link points to the getting started page of the website.
=> Fixed old link to introduction

CHANGELOG.md, cargo-insta/src/cli.rs
The `-p` flag is not part of `TargetArgs` but the test argument. As a result it was handled correctly when stepping through the folder tree when snapshot deletion was requested. This now fixes this behavior. Additionally if the last snapshot test was removed an IO error was triggered which is no longer the case now.
This fixes #201
=> This fixes cargo-insta not handling -p correctly when deleting snapshots

CHANGELOG.md, src/output.rs, src/runtime.rs, src/snapshot.rs
Previously line numbers for assertions were intentionally not included as they are getting stale quickly. However immediately after the creation of a snapshot they are still accurate and useful for display in insta.
This fixes #191
=> Include assertion line numbers in snapshot files

CHANGELOG.md, Cargo.toml, src/macros.rs, src/runtime.rs, tests/snapshots/test_inline__unnamed_thread_single_line-2.snap, tests/snapshots/test_inline__unnamed_thread_single_line.snap, tests/test_clash_detection.rs, tests/test_inline.rs
We used to detect the snapshot names form the current thread.  This has
been very unrealiable in a lot of cases.  This changes the behavior so
that the function name is used instead by using `std::any::type_name`.
This does change behavior slightly but most users should not notice this
change except if they relied on helper functions.  In that case using a
macro is a better solution most likely.
Refs #127 and #105
=> Detect snapshot names from function names

cargo-insta/src/cargo.rs, cargo-insta/src/inline.rs
The code assumed that inline snapshots do not linger around for too long. This caused panics if the files were changed between when the inline snapshot was created and it was applied. Now this case is silently ignored.
Fixes #220
=> Do not panic on outdated inline snapshots

CHANGELOG.md, cargo-insta/src/cli.rs
This changes cargo-insta to return a non zero status code when snapshots are left for review.
Fixes #222
=> Set non zero status code for pending tests

src/snapshot.rs
The generated inline strings for snapshots with a single trailing
newline currently look something like this:
```
insta::assert_snapshot!(stdout, @"foo
");
```
The unindented line there is distracting. I think it looks neater with
the block-style strings, like this:
```
insta::assert_snapshot!(stdout, @###"
foo
"###);
```
I suspect the reason it isn't currently generated like that is just an
oversight caused by the fact that Rust's `str::lines()` returns a
single line for that kind of strings. This patch fixes it by looking
for `\n` characters instead.
=> Use inline block format also for strings of form "foo\n"

CHANGELOG.md, cargo-insta/src/cli.rs
=> Add support for --no-quiet to cargo-insta test

CHANGELOG.md, src/lib.rs, src/runtime.rs, src/snapshots/doctest_runtime_rs__named.snap, src/snapshots/doctest_runtime_rs__unnamed_doctest.snap
This adds some detection code so that doctests do not get really bad snapshot names that are unstable.
=> Added improved doctest support

CHANGELOG.md, cargo-insta/src/cli.rs, src/macros.rs, src/output.rs, src/runtime.rs, src/settings.rs, src/snapshot.rs, tests/snapshots/test_settings__snapshot_with_description.snap, tests/snapshots/test_settings__snapshot_with_description_and_info.snap, tests/test_settings.rs
This also refactors the internals for modifying settings via macros so
it's a perfect match to the public interface and adds a new `omit_expression`
flag to the settings to prevent the default expression to be written.
Fixes #238
Fixes #177
=> Added info and description fields

CHANGELOG.md, Cargo.toml, src/filters.rs, src/lib.rs, src/runtime.rs, src/settings.rs, src/snapshot.rs, tests/test_filters.rs
This adds a new filters feature which lets one run a regex over the snapshot before storing. This is useful for snapshots that originate in string form where redactions cannot be applied.
=> Added new filters feature

CHANGELOG.md, src/runtime.rs
Turns out due to doctest isolation this is just not possible currently.
Fixes #244
=> Disallow unnamed snapshots in doctests

.github/workflows/minver.yml, Cargo.toml, Makefile
This is not *critical*, as doing minimal version resolution requires nightly or non-automatic version selection. However, it's still good practice to try to keep minimal-versions correct and specify the versions that you need.
=> Fix build with minimal versions resolution

src/settings.rs, tests/test_settings.rs
The current `Settings::bind_to_thread` is very hard to use as it has no resetting drop guard.
=> Add support for Settings::bind_to_scope

src/snapshot.rs
Fixes #247 under the assumption that a change in nextest lands (https://github.com/nextest-rs/nextest/pull/417).
=> Added Support for NEXTEST_RUN_ID

CHANGELOG.md, src/runtime.rs
=> Resolve an issue where inline snapshot tests refused to work in doctests

Cargo.toml, src/lib.rs, src/macros.rs, src/serialization.rs
This turns on `assert_json_snapshot!` and `assert_yaml_snapshot!` by default again for one release but introduces a deprecation warning.
This fixes #259
=> Create a smoother transition to new feature toggles

Cargo.toml, cargo-insta/Cargo.lock, src/env.rs, src/serialization.rs
`serde_yaml` in 0.9 changed the output format and dropped `yaml-rust`. Since as of #255 we now use `yaml-rust` directly anyways we might as well shoot too birds with one stone. This avoids an extra dependency and it retains the same serialization format that we had before.
Fixes #256
=> Switch from serde_yaml to rust-yaml for serialization

Cargo.toml, src/content/formats.rs, src/content/json.rs, src/serialization.rs, src/snapshot.rs
This removes `serde_json` for a built-in emitter. This gives us more stable snapshots but this still needs tests to ensure the output matches what was there before.
Fixes #258
=> Drop serde_json entirely for snapshot emission

CHANGELOG.md, src/runtime.rs
=> Add a warning that doctests do not support inline updates

cargo-insta/integration-tests/Cargo.toml, cargo-insta/src/cli.rs, src/glob.rs, src/macros.rs
Alternative implementation to #275.  It supports more than one glob filter and uses default separator handling.
Fixes #274
=> Implement INSTA_GLOB_FILTER

cargo-insta/src/cli.rs, src/glob.rs, src/macros.rs, src/runtime.rs
This is an experimental feature to address https://github.com/mitsuhiko/insta/discussions/283
=> Defer glob failures

cargo-insta/src/cli.rs
This adds a `INSTA_TEST_RUNNER` environment variable to control if `cargo-test` or `nextest` should be used.  The default is `auto` which will eventually prefer `nextest` over `cargo-test` but for now stays with `cargo-test`.
It still needs to use `cargo test --doc` to run doctests due to https://github.com/nextest-rs/nextest/issues/16
Refs #282
=> Add nextest support to cargo-insta

cargo-insta/src/cli.rs
=> Added missing test command args

src/output.rs
This renders some invisibles which should also help with ansi codes.
Fixes #300
=> Render some invisibles in diffs

cargo-insta/src/cli.rs
A very incomplete solution to https://github.com/mitsuhiko/insta/issues/319. 
Until we can agree on a good path forward, this seems like a good tradeoff, given the likelihood that someone has a subset of snap files being gitignored, vs. every standard run of `cargo-insta`. 
But totally fine to close if you don't agree @mitsuhiko
=> Only print warning if no snapshots found

cargo-insta/src/cli.rs, src/env.rs, src/glob.rs, src/lib.rs, src/macros.rs, src/runtime.rs
This changes the insta and cargo-insta internals so that a tool config is loaded from `.config/insta.yaml`.
Fixes #282
=> Implement basic tool config

CHANGELOG.md, cargo-insta/src/cargo.rs, cargo-insta/src/cli.rs, src/env.rs, src/lib.rs
This renames the confusing `--no-ignore` to `--include-ignored` and adds a new `--include-hidden` flag. The latter is used to instruct insta to walk into hidden folders. Additionally both are now also available as tool config.
Refs #326
=> Add ways to walk into hidden folders

CHANGELOG.md, cargo-insta/src/cli.rs, src/env.rs, src/lib.rs
=> Add new --unreferenced option to control unreferenced snapshot behavior

cargo-insta/src/cargo.rs, cargo-insta/src/cli.rs, cargo-insta/src/walk.rs, src/env.rs, src/lib.rs
This changes the current warning that comes up whenever ignored or hidden paths exists to one that only comes up if actual snapshots are found in those locations.
Refs #329
=> Warn only if snapshots are found in hidden or ignored locations

src/runtime.rs, src/snapshot.rs
Today force update will typically report lots of changed snapshots even if they did not actually change. Additionally it generates pending snapshot files for inline snapshots which result in absolutely no changes. This changes the behavior to compare the serialized contents to the current ones and only write a change if there is one.
Fixes #333
=> Implement better force update behavior that ignores no-ops

cargo-insta/src/inline.rs
It's possible for the patcher to encounter snapshots where an internal assertion fails. Rather than panicking, treat the erroneous snapshot as outdated.
Fixes #340
=> Fix a patcher panic

cargo-insta/src/cli.rs
If we would bump the MSRV to 1.64.0 we could switch from structopt to clap, which would let us further improve the `cargo insta help test` output by grouping options with the `help_heading` option (see https://github.com/charliermarsh/ruff/pull/2155 for an example) ... and then we could also have the `TestRunner` and `UnreferencedSnapshots` enums derive [ValueEnum](https://docs.rs/clap/latest/clap/trait.ValueEnum.html), which would mean we would no longer have to duplicate the `possible_values` in `cargo-insta`.
But seeing that you haven't yet decided on the MSRV issue #289, I just made the improvements that structopt supports :)
=> Improve `cargo insta help` output

CHANGELOG.md, Makefile, cargo-insta/src/cli.rs, src/utils.rs
=> Added cargo insta test --check and CI detection

cargo-insta/src/cli.rs, src/lib.rs, src/macros.rs, src/output.rs, src/runtime.rs, tests/test_allow_duplicates.rs
This adds a new macro called `allow_duplicates!`. When a block of code is wrapped with it, every snapshot assertion can be visited more than once. In that case all of the snapshot assertions in a loop etc. have to match with each other and if not, an assertion error is raised.
Motivational example:
```rust
#[test]
fn test_basic_duplicates_passes() {
allow_duplicates! {
for x in (0..10).step_by(2) {
let is_even = x % 2 == 0;
assert_debug_snapshot!(is_even, @"true");
}
}
}
```
Fixes #313
=> Add support for allow_duplicates!

Cargo.toml
CSV now requires 1.60, trying to see if pinning to 1.1.6 works to retain lower MSRV.
=> Pin CSV to 1.1.6

CHANGELOG.md, cargo-insta/src/cli.rs, src/lib.rs, src/output.rs
Added support for hiding or showing diffs in review
Fixes #338
=> Added support for hiding diffs / showing snapshots in review

src/glob.rs, src/macros.rs, tests/glob_submodule/mod.rs, tests/glob_submodule/snapshots/test_glob__glob_submodule__basic_globbing_absolute_dir@goodbye.txt.snap, tests/glob_submodule/snapshots/test_glob__glob_submodule__basic_globbing_absolute_dir@hello.txt.snap, tests/glob_submodule/snapshots/test_glob__glob_submodule__basic_globbing_nested_parent_dir_base_path@a__file.txt.snap, tests/glob_submodule/snapshots/test_glob__glob_submodule__basic_globbing_nested_parent_dir_base_path@b__file.txt.snap, tests/glob_submodule/snapshots/test_glob__glob_submodule__basic_globbing_nested_parent_glob@a__file.txt.snap, tests/glob_submodule/snapshots/test_glob__glob_submodule__basic_globbing_nested_parent_glob@b__file.txt.snap, tests/glob_submodule/snapshots/test_glob__glob_submodule__basic_globbing_parent_dir@goodbye.txt.snap, tests/glob_submodule/snapshots/test_glob__glob_submodule__basic_globbing_parent_dir@hello.txt.snap, tests/glob_submodule/snapshots/test_glob__glob_submodule__globs_follow_links_parent_dir_base_path@goodbye.txt.snap, tests/glob_submodule/snapshots/test_glob__glob_submodule__globs_follow_links_parent_dir_base_path@hello.txt.snap, tests/glob_submodule/snapshots/test_glob__glob_submodule__globs_follow_links_parent_dir_glob@goodbye.txt.snap, tests/glob_submodule/snapshots/test_glob__glob_submodule__globs_follow_links_parent_dir_glob@hello.txt.snap, tests/test_glob.rs
The new three-arg glob! allows users to specify the base directory the glob is working against. This works around the limitation that blobs like `../foo/*.json` do not resolve with the current walkdir + globset implementation.
This allows the usage of `glob!` in nested situations where the globbed files are in a parent directory:
```
src
├── main.rs
├── snapshots
│   └── insta_glob_test__insta_glob_dir.snap
├── submod
│   └── mod.rs -- glob! tests are here
└── test_data
└── foo.json
```
```rust
glob!("../test_data", "*.json", |path| { ... })
```
=> glob!: Add three-arg version to specify base_path

CHANGELOG.md, src/lib.rs, src/redaction.rs, tests/snapshots/test_redaction__rounded_redaction.snap, tests/test_redaction.rs
=> Added rounded_redaction

src/macros.rs
explaining that `Debug` is used in pretty-print mode
=> edit docs of `assert_debug_snapshot`

src/glob.rs
Hi,
I noticed this small typo while using glob!.
=> Fix minor typo in glob error message

.github/workflows/clippy.yml, .github/workflows/minver.yml, .github/workflows/rustfmt.yml, .github/workflows/tests.yml
The following updates are performed:
* update [`actions/checkout`](https://github.com/actions/checkout) to v3
* replace [unmaintained](https://github.com/actions-rs/toolchain/issues/216) `actions-rs/toolchain` by [`dtolnay/rust-toolchain`](https://github.com/dtolnay/rust-toolchain)
Still using the outdated / unmaintained actions will generate several warnings in CI runs, for example in https://github.com/mitsuhiko/insta/actions/runs/4616241256:
> Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions-rs/toolchain@v1. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
The PR will get rid of those warnings.
=> Update GitHub Actions CI

cargo-insta/src/cli.rs
Two parts to https://github.com/mitsuhiko/insta/issues/367 :
- The libtest output, which this PR solves
- I've hand-tested it
- Possibly this becomes moot if `cargo` is changed to handle more of the output
- The `insta` output when insta is called by libtest; e.g. the diffs. There's not much we can do from `cargo-insta`, but [`CLICOLOR_FORCE`](http://bixense.com/clicolors/) works, because `console` reads it
=> Pass `--color=...` to libtest

cargo-insta/Cargo.lock, cargo-insta/Cargo.toml, cargo-insta/src/inline.rs
I'm occasionally seeing a chunk of the file cut off when using insta with https://dystroy.org/bacon/, which restarts on any file change. The proposed code does an atomic rename, preventing this.
It does add a dependency though, so up to you on the tradeoff.
=> Write inline snapshots with atomic rename

cargo-insta/src/cargo.rs, cargo-insta/src/cli.rs, cargo-insta/src/main.rs, cargo-insta/src/walk.rs
Feel free to close if not helpful...
=> Apply Clippy changes

CHANGELOG.md, cargo-insta/src/cli.rs
I wasn't sure how deliberate this choice was -- totally fine to close if it was. 
As a user, I always want it to honor the `--accept` arg.
=> Simpler accept behavior on non-insta failures

src/runtime.rs
Fix #336 
The issue is caused due to not canonicalize the stripped prefix when localizing the path.
For example in my environment i get `"D:\\Rust\\insta"` to strip from `"\\\\?\\D:\\Rust\\insta\\tests\\inputs\\goodbye.txt"` while when canonicalized becomes the correct prefix `"\\\\?\\D:\\Rust\\insta"`.
I used unwrap with the assumption that if canonicalize fails the previous call to canonicalize would also fail and it doesn't arrive at the unwrap.
=> Fix glob! input_file on Windows

cargo-insta/src/cargo.rs, cargo-insta/src/cli.rs
As ever for these, feel free to ignore
=> Clippy changes to `cargo-insta`

.github/workflows/tests.yml, CHANGELOG.md, src/runtime.rs
=> Fixed input_file on windows

src/macros.rs
=> Suppress needless_raw_string_hashes clippy lint on inline snapshots

cargo-insta/src/cli.rs
=> cargo-insta: allow passing --profile

cargo-insta/src/cli.rs
Now the message is aware of whether there is an old snapshot or not.
=> cargo-insta: edit reject message

cargo-insta/src/cargo.rs, cargo-insta/src/cli.rs, cargo-insta/src/container.rs, cargo-insta/src/inline.rs, cargo-insta/src/utils.rs, cargo-insta/src/walk.rs
Items which are marked pub are not considered by rustc's dead code
lints, allowing obvious bugs like the one fixed in 84cddf9c7045a2769c6b06dd0259640c0ba2df5c.
This exposed the fact that `PendingSnapshot.id` is unused, so `#[allow(dead_code)]` is added to that field.
=> cargo-insta: reduce visibility of all items

cargo-insta/Cargo.lock, cargo-insta/Cargo.toml, cargo-insta/src/cargo.rs, cargo-insta/src/cli.rs, cargo-insta/src/walk.rs
Prior to this change --manifest-path only worked properly if it pointed to the root of a non-virtual workspace.
Rewrite all the cargo interaction to use cargo-metadata which crucially provides `Metadata::resolve::root` which is used to determine which package --manifest-path was pointing to.
https://doc.rust-lang.org/cargo/reference/workspaces.html#virtual-workspace
=> cargo-insta: fix --manifest-path <virtual-workspace>

CHANGELOG.md, cargo-insta/src/cli.rs, cargo-insta/src/container.rs
=> Sort snapshot containers

CHANGELOG.md, src/macros.rs, tests/snapshots/test_redaction__with_random_value_and_trailing_comma_match.snap, tests/snapshots/test_redaction__with_random_value_csv_match.snap, tests/snapshots/test_redaction__with_random_value_json_match.snap, tests/snapshots/test_redaction__with_random_value_ron_match.snap, tests/snapshots/test_redaction__with_random_value_toml_match.snap, tests/test_redaction.rs
This adds a new optional redactions syntax for rustfmt support:
```rust
#[cfg(feature = "yaml")]
#[test]
fn test_with_random_value_and_trailing_comma_match() {
assert_yaml_snapshot!(
&User {
id: 11,
username: "john_doe".to_string(),
email: Email("john@example.com".to_string()),
extra: "".to_string(),
},
match .. {
".id" => "[id]",
}
);
}
```
Fixes #419
=> Added alternative redactions syntax for rustfmt

src/env.rs
The usual new lint fixes. Just one violation and the lint seems good here
=> Fix new `#[allow(clippy::get_first)]`

CHANGELOG.md, src/snapshot.rs, tests/test_inline.rs
Previously leading whitespace caused snapshots to mismatch. This is an issue for inline snapshots where the code that removes leading indentation cannot express this properly. For now solve this by ignoring leading newlines in addition to trailing spaces which are already ignored.
Ideally future versions of the macros would inject a special character into a snapshot if leading and trailing newlines play a role.
=> Ignore leading newlines on snapshot comparison

cargo-insta/src/cli.rs
Currently if a test panics, insta can remove basically all the snapshots in the project. This changes the behavior to only delete when tests are successful.
Possibly there's a more precise approach? Though in the meantime, this does seem better...
=> Only delete unreferenced snapshots after a successful test run

CHANGELOG.md, src/snapshot.rs
Followup to #444 so that diffs do not show incorrect diffs.
=> Trim on diff

cargo-insta/src/cli.rs, src/env.rs
The docs had `INSTA_FORCE_UPDATE`, but actually `INSTA_FORCE_UPDATE_SNAPSHOTS` was used. I kept the former, since that's consistent with the config file & cli options
Docs are here: https://github.com/mitsuhiko/insta/blob/7c00b0b037105481fd6548a1b66a1b9e4ed2efcb/src/lib.rs#L197
=> Align env var with docs

src/env.rs
Restores support for older insta versions in cargo insta broken by #449.
=> Restore cargo-insta compat with older insta

cargo-insta/src/container.rs, src/content/mod.rs, src/lib.rs, src/snapshot.rs
I tracked down https://github.com/mitsuhiko/insta/issues/380 at last.
This doesn't solve the problem, but does show which file is being deleted, so it's not such a mystery. A future PR could change how these are handled so it's more permissive.
For example:
```
error: File error for `/Users/maximilian/workspace/prql/prqlc/prqlc-parser/src/.lexer.rs.pending-snap': No such file or directory (os error 2)
```
=> Better missing file errors

CHANGELOG.md, src/macros.rs, tests/snapshots/test_basic__Testing.snap, tests/snapshots/test_basic__trailing_commas-2.snap, tests/snapshots/test_basic__trailing_commas.snap, tests/snapshots/test_redaction__with_random_value_and_match_comma-2.snap, tests/snapshots/test_redaction__with_random_value_and_match_comma.snap, tests/test_basic.rs, tests/test_inline.rs, tests/test_redaction.rs
This was implemented for some macros but not others (possibly this was my mistake when simplifying the macros...). This centralizes their handling in two central macros.
Inline macros don't work, because of how we replace the values, so we still need to fix those. But I ran out of time on this so pushed the partial fix.
=> Allow trailing commas to work for file snapshots

insta/src/snapshot.rs
Fixes #401 as well as most (but not all) of #477
=> Fix snapshot & module name extraction

README.md, insta/src/snapshot.rs
This fixes the issues in https://github.com/mitsuhiko/insta/issues/477, stacked on https://github.com/mitsuhiko/insta/pull/483.
It's possible I've still missed something (though the excellent repro in #477 passes). I realize that there are plenty of areas I'm still unsure about in the repo... Possibly some slower integration tests with sample projects would be worthwhile; though they don't make for the nimblest of tests...
=>  Fix `require_full_match`

cargo-insta/src/container.rs
=> Be robust to removing pending snapshots during review

cargo-insta/src/inline.rs, cargo-insta/tests/snapshots/main__test_basic_utf8_inline.snap, cargo-insta/tests/snapshots/main__test_json_inline.snap, cargo-insta/tests/snapshots/main__test_yaml_inline.snap, cargo-insta/tests/test-input/test_basic_utf8_inline.rs, cargo-insta/tests/test-input/test_json_inline.rs, cargo-insta/tests/test-input/test_yaml_inline.rs, insta/src/macros.rs, insta/tests/test_inline.rs, insta/tests/test_redaction.rs
After using https://github.com/mitsuhiko/insta-cmd/pull/12 for a bit, I noticed that `cargo insta test` would not pick up on mismatches in inline snapshots with trailing commas.
This PR fixes that and also allows trailing commas for inline snapshots in other macros.
This PR uses code from #454 by @max-sixty.
=> Allow trailing commas in inline snapshots

cargo-insta/src/walk.rs, insta/src/lib.rs, insta/src/runtime.rs, insta/src/snapshot.rs
This attempts to clarify when snapshots are written to pending `.snap.new` files vs. to overwriting `.snap` files vs. doing nothing to snapshots.
It also changes `.with_extension(...)`, lmk if you prefer those on a separate PR
=> Improve docs for snapshot updates

vscode-insta/package.json, vscode-insta/src/PendingSnapshotsProvider.ts, vscode-insta/src/cargo.ts, vscode-insta/src/extension.ts, vscode-insta/src/insta.ts
This is a naive implementation where we just search for cargo lockfiles to find cargo roots.
It's good enough imo and isn't much worse than the previous impl
Closes #471
=> Fix VSCode plugin not recognizing crates in subfolders

insta/src/runtime.rs
Spotted this as an aside — we don't use the function to name doctests so no need to thread these args through
=> (minor) Simplify `detect_snapshot_names`

cargo-insta/src/cli.rs
=> Remove `name` field for inline snapshot

CHANGELOG.md, cargo-insta/src/cli.rs
I did some more testing. There are some corner-cases where it doesn't work; for example if `info` is used it fails, because our serializer / deserializer doesn't roundtrip.
For example; from the insta tests, One is `Map`; the other a `Struct`:
```
[insta/src/snapshot.rs:440:20] self.metadata.trim_for_persistence() = MetaData {
source: None,
assertion_line: None,
description: Some(
"The snapshot is four integers",
),
expression: None,
info: Some(
Map(
[
(
String(
"env",
),
Map(
[
(
String(
"ENVIRONMENT",
),
String(
"production",
),
),
],
),
),
(
String(
"cmdline",
),
Seq(
[
String(
"my-tool",
),
String(
"run",
),
],
),
),
],
),
),
input_file: None,
}
[insta/src/snapshot.rs:441:24] other.metadata.trim_for_persistence() = MetaData {
source: None,
assertion_line: None,
description: Some(
"The …
```
=> Mark `require-full-match` as experimental

CHANGELOG.md, cargo-insta/src/cli.rs, insta/src/runtime.rs
Use an env var to indicate when we're running with `cargo insta`, don't suggest to do so if we already are
(I may try and change what `--check` does — don't think in necessarily needs to fail fast, but this fixes the message for now)
=> Print a better message when running with `--check`

CHANGELOG.md, insta/src/runtime.rs, insta/src/snapshot.rs
Running `require-full-match` without `cargo-insta` (or with `cargo insta --check`) wasn't working on inline snapshots, since those snapshots don't have metadata.
I'm also going to PR to make `require-full-match` experimental, since I've also found some corner cases where it doesn't work yet.
=> Fix `require-full-match` working without cargo-insta on inline snapshots

insta/src/snapshot.rs
This had been broken by #496, which is now reverted and replaced by a TODO.
=> Fix writing metadata

insta/src/macros.rs, insta/tests/test_inline.rs
The pretty-print format of debug is generally extremely verbose. It's great for complex objects, but for simple ones, the compact form of debug is far more suitable. This PR adds a `assert_compact_debug_snapshot` similar to `assert_compact_json_snapshot`.
=> feat: add `assert_compact_debug_snapshot`

CHANGELOG.md, insta/src/snapshot.rs
Would be nice to remove this sort of code at some point. Maybe we need to wait for 2.0 though. But either way, this encourages updating to newer formats.
=> Print a warning for old snapshot formats

.github/workflows/tests.yml
I've been using this approach to test `cargo-insta` locally; would it make a reasonable test for CI too?
=> Run the in-tree version of cargo-insta in CI

cargo-insta/Cargo.toml, cargo-insta/src/inline.rs
Need to upgrade `structopt` and then we'll reduce the compile time by coalescing on a single `syn`
~Edit: possibly we need to wait for a newer MSRV~
Ready to merge
=> Upgrade to syn 2

insta/src/snapshot.rs
The test added in 816df8856c28 doesn't seem to test what it was
supposed to test - it still passses after replacing `l.is_empty() { 0
} else { indentation }` by just `indentation`. With the change in this
patch, the test fails with that modification.
=> test: make test for #88 effective

Cargo.lock, cargo-insta/Cargo.toml, cargo-insta/tests/main.rs
This splits out the changes in the test code from #532 in order to make that diff smaller.
It divides  the building of the test case files from the test case files on disk + running the test, which make the structs simpler & more obvious
=> Improve integration tests

CHANGELOG.md
This follows up https://github.com/mitsuhiko/insta/pull/514 and use the same pattern of:
> Added support for compact JSON snapshots. (#288)
@max-sixty
=> docs: Update CHANGELOG for assert_compact_debug_snapshot

cargo-insta/Cargo.toml, insta/Cargo.toml
Prepping for release -- these are locked in `Cargo.lock`. Locking them in `Cargo.toml`s could cause a conflict if used as a dependency in combination with other libraries which require a more recent version. This is more of a risk for `insta` rather than `cargo-insta`.
(I'm actually looking forward to the MSRV resolver!)
=> Don't enforce locking in Cargo.toml

cargo-insta/src/cli.rs, cargo-insta/src/utils.rs
We don't use this yet, but could be helpful in areas such as #482
=> Add `cargo-insta` version to env vars

insta/src/snapshot.rs
These are not actually needed for multiline strings...
=> Adjust snapshot formatting tests

CHANGELOG.md, insta/src/filters.rs
Currently filters must be `Vec`s:
```rust
insta::with_settings!({filters => vec![
(r"tmp\/\.tmp.*\/", "[TEMPDIR]"),
(r"var\/.*\/\.tmp.*\/", "[TEMPDIR]"),
]}, { }
```
However, using an array could be cleaner:
```rust
insta::with_settings!({filters => [
(r"tmp\/\.tmp.*\/", "[TEMPDIR]"),
(r"var\/.*\/\.tmp.*\/", "[TEMPDIR]"),
]}, { }
```
And finally, it enables the filters to be extracted into a `const`:
```rust
const FILTERS: [(&'static str, &'static str); 2] = [
(r"tmp\/\.tmp.*\/", "[TEMPDIR]"),
(r"var\/.*\/\.tmp.*\/", "[TEMPDIR]"),
];
insta::with_settings!({filters => FILTERS}, { }
```
=> Generalise filters to support `IntoIterator` types, not just `Vec`s

CHANGELOG.md, cargo-insta/tests/main.rs, insta/src/runtime.rs
We previously excluded these. But it's somewhat required for #563, and I don't think there's a big downside -- we only generate pending files when a snapshot doesn't match of `--force-update-snapshots` is passed.
=> Enable inline snapshots to be force-updated

cargo-insta/tests/main.rs
From https://github.com/mitsuhiko/insta/pull/482
=> Add integration test for force updating

CHANGELOG.md, insta/src/content/serialization.rs
Fixes potential crashes on Rust 1.81.
=> Implement total ord for Key

cargo-insta/src/walk.rs, cargo-insta/tests/main.rs
This was fixed in 1.40, added a test out of #593 to confirm
=> Add test for reporting correct number of snapshots

Cargo.lock
=> Increase `hermit_abi` in `Cargo.lock`

CHANGELOG.md, cargo-insta/src/cli.rs, cargo-insta/src/container.rs, cargo-insta/src/walk.rs, cargo-insta/tests/main.rs, insta/src/lib.rs, insta/src/output.rs, insta/src/runtime.rs, insta/src/snapshot.rs
This solves the issue in #573 for the moment:
- When `--force-update-snapshots` in passed, we only update inline snapshots when there's some difference _within_ the string, such as an additional linebreak at the start or the end
- We no longer update the surrounding hashes. In the existing code, this happened because we were writing too many inline snapshots, not because we were actually checking the number of hashes
- Checking the number of hashes isn't easy to do — reason outlined at https://github.com/mitsuhiko/insta/pull/573#issuecomment-2323500808
- The main change in the code is that we store the unnormalized snapshot and then normalize when we need to. The existing code stored the normalized version, which meant we couldn't evaluate whether the unnormalized versions were different …
=> Adjust force-update on inline snapshots to only view within the string

cargo-insta/src/container.rs, insta/src/output.rs, insta/src/runtime.rs, insta/src/settings.rs, insta/src/snapshot.rs
Helpful to me, hopefully helpful to others
=> Add a couple of docstrings / small refactors

insta/src/content/yaml/vendored/emitter.rs
This fixes an instance of [`warn(elided_named_lifetimes)`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_lint/builtin/static.ELIDED_NAMED_LIFETIMES.html) which should be uncontroversial.
```
warning: elided lifetime has a name
--> insta/src/content/yaml/vendored/emitter.rs:106:51
|
105 | impl<'a> YamlEmitter<'a> {
|      -- lifetime `'a` declared here
106 |     pub fn new(writer: &'a mut dyn fmt::Write) -> YamlEmitter {
|                                                   ^^^^^^^^^^^ this elided lifetime gets resolved as `'a`
|
= note: `#[warn(elided_named_lifetimes)]` on by default
warning: `insta` (lib) generated 1 warning
```
I know that this currently only "affects" the nightly compliler. Fixing in case this becomes a warn by default lint in the future ^^
Docs on this lint:
- …
=> chore: fixed `warn(elided_named_lifetimes)`

insta/src/runtime.rs
Small refactor — standardizes functions operating on a snapshot context as methods
=> Move a few functions onto context object

cargo-insta/tests/main.rs, insta/src/env.rs, insta/src/glob.rs, insta/src/macros.rs, insta/src/runtime.rs
Intended to fix #575. Though after some iterations, it ends up being a code-clean-up. I'm not sure how `CARGO_MANIFEST_DIR` is leaking through — it's only referenced by `env!` rather than `env::var`, so should only matter at compile time.
Added a pretty thorough integration test (albeit maybe a bit too complicated)
=> Consolidate onto `INSTA_WORKSPACE_ROOT`

cargo-insta/src/main.rs, cargo-insta/tests/main.rs, insta/src/content/json.rs, insta/src/content/mod.rs, insta/src/content/serialization.rs, insta/src/content/yaml/vendored/emitter.rs, insta/src/content/yaml/vendored/parser.rs, insta/src/content/yaml/vendored/yaml.rs, insta/src/env.rs, insta/src/lib.rs, insta/src/macros.rs, insta/src/redaction.rs, insta/src/runtime.rs, insta/src/settings.rs, insta/src/snapshot.rs
While browsing the docs on docs.rs, I noticed that there are a few items which are not linked.
This PR tries to improve this situation.
Drawing attention to one thing which might be controversial:
In the current codebase, the usage of `[´foo´](Self::foo)` and `[´Self::foo´]` (and related links) are a bit inconsistent. I have changed all to the `[´Self::foo´]` format. Please let me know if you prefer the first and I can change them to that format.
I have verified this change via adding the following (somewhat agressive) docs-related lints and running `RUSTDOCFLAGS="--cfg=docsrs" cargo +nightly doc --no-deps --all-features` and `cargo clippy --all-features --all`.
```rust
#![warn(clippy::doc_markdown)]
#![warn(rustdoc::all)]
```
=> docs: improved the linking inside and outside of the crate

cargo-insta/Cargo.toml, cargo-insta/src/cargo.rs, cargo-insta/tests/main.rs
Fixes https://github.com/mitsuhiko/insta/issues/625
As ever, the reason is a bit different from the one I initially understood. It's actually that we're reducing the paths by whether one prefixes the other. But in this case the path is only a prefix before it's canonicalized!
On the upside, this case will now work without `--workspace-root`.
=> Canonicalize snapshot paths before reducing

cargo-insta/src/cli.rs, cargo-insta/src/walk.rs, cargo-insta/tests/main.rs
A previous fix of mine broke this, because it wasn't consistent on whether an extension was `.snap` or `snap`.
As part of this fix, it also now works for non-standard extensions. And we have an integration test.
=> Fix `--unreferenced` flag

cargo-insta/src/cli.rs, insta/src/env.rs
If someone passes `.snap` as an extension, they'll get files of `foo..snap`, which is probably not what they want.
We could strip the leading `.`
Also some light refactoring
=> Warn if extension is passed with a leading dot

cargo-insta/src/cli.rs, cargo-insta/src/container.rs, insta/src/snapshot.rs
Since the binary snapshots have merged, there are some methods which return `Some` if the enum is a certain variant. We can just use pattern matching for that.
(Note that the code is a bit complicated and has lots of repetition of 'kind'-like fields; but wanted to merge the binary snapshots feature before cleaning up the internals
=> Remove some methods from `SnapshotContents`

cargo-insta/tests/main.rs, insta/src/snapshot.rs
Otherwise `--force-update-snapshots` would never be satisfied.
Note comment inline: rather than spend more time on this, let's just try and get one of those two in:
```
// Note that we previously would match the exact values of the
// unnormalized text. But that's too strict — it means we can
// never match a snapshot that has leading/trailing whitespace.
// So instead we check it matches on the latest format.
// Generally those should be the same — latest should be doing
// the minimum normalization; if they diverge we could update
// this to be stricter.
//
// (I think to do this perfectly, we'd want to match the
// _reference_ value unnormalized, but the _generated_ value
// normalized. That way, we can get the But at the moment we
// don't distinguish between which is which in our …
```
=> Fix `--require-full-match` on inline snapshots with leading newlines

cargo-insta/src/cli.rs, insta/src/snapshot.rs
Not sure the old code was working, this is simpler
=> Better deprecation warning for `--no-force-pass`

CHANGELOG.md, cargo-insta/src/cli.rs, cargo-insta/tests/main.rs, insta/src/runtime.rs, insta/src/snapshot.rs
As discussed in #630
Will wait for a few days before merging.
=> `--force-update-snapshots` always writes, and implies `--accept`

insta/src/lib.rs
As discussed in #610 it probably makes sense to be explicit about the `internals` module not being guaranteed to be stable.
I also noticed that `TextSnapshotKind` gets exposed globally. This was added in #581 when it was still called `SnapshotKind`. I wonder if this is necessary to expose toplevel.
=> Add warning about stability to doc comment for internals module

CONTRIBUTING.md, cargo-insta/src/cli.rs, cargo-insta/src/utils.rs, insta/src/env.rs
...otherwise it doesn't respond to `--manifest-path`. If it does raise an error, we just continue after printing a warning, rather than panicking.
Also added some docs on running a reproducible example in another path.
(I've also found a bug with `--workspace-root`, will handle separately, and will add a test for both)
=> Collect `insta` version in standard `cargo metadata` call

.gitignore, Cargo.lock, cargo-insta/Cargo.toml, insta/Cargo.toml, insta/src/env.rs, insta/src/glob.rs, insta/src/runtime.rs, insta/src/settings.rs, insta/src/snapshot.rs
Hi, since both crates are now on MSRV >= 1.60, we can now use `once_cell` over `lazy_static` [0]
[0] https://github.com/matklad/once_cell/blob/4fbd4a53509ca59c8e09efc2ab0a22f21de70f7e/Cargo.toml#L7
=> Replace `lazy_static` with `once_cell`

cargo-insta/src/cli.rs
Not a big deal, but I think we can just defer
=> Defer to `cargo metadata` to evaluate the workspace root

cargo-insta/tests/functional/main.rs
This broke on updating the tag to 1.42. I don't know exactly why and 5 minutes of looking through wasn't enough. That's not a great state to be in, but merging to ensure test pass on `master`
=> Update test output for `snapshot_text` change

CHANGELOG.md, insta/src/snapshot.rs
Fixes at least some of #712 (not confident it fixes all of it, but wanted to get it out quickly)
=> Improved handling of control characters in inline snapshots

CHANGELOG.md, insta/src/snapshot.rs
fixes #715
`'\0'.is_control() == true`, so I removed that special case.
=> Don't escape snapshots containing tab and ESC control characters

CHANGELOG.md, cargo-insta/src/inline.rs, insta/src/snapshot.rs
- Adds support for non-space indention - even a "weird" mix of e.g. tabs and spaces.
- Note, I had to add `String` field to the `Visitor` struct becasue the whitespace before
the macro keyword is not included in the syn crate.
- I only added a few new test cases with pure tabs or a combination of tabs and white spaces
as most existing tests were also impacted by the change (and thus also tested the feature).
- Added changelog entry.
=> Add support for non-space indention

cargo-insta/src/inline.rs
```
thread 'main' panicked at cargo-insta/src/inline.rs:130:22:
byte index 32 is out of bounds of `    insta::assert_snapshot!(`
```
=> Fix crash on scanning indentation of arbitrary lines

CHANGELOG.md, cargo-insta/src/inline.rs, cargo-insta/tests/functional/inline.rs
#712
There are two problems:
1. single-line snapshot isn't deduplicated
2. the last assertion in the `allow_duplicates!` block is always chosen
```rust
#[test]
fn test_dup() {
for _ in 0..2 {
insta::allow_duplicates! {
// shouldn't be updated twice
insta::assert_snapshot!("foo", @"");
}
}
}
```
```rust
#[test]
fn test_bad_location() {
for _ in 0..2 {
insta::allow_duplicates! {
// each snapshot should be updated accordingly
insta::assert_snapshot!("1", @"
1a
1b
");
insta::assert_snapshot!("2", @"
2a
2b
");
}
}
}
```
=> Fix inline snapshot handling within `allow_duplicates!` block

CHANGELOG.md, insta/src/lib.rs, insta/src/macros.rs
This change replaces all unqualified references in macros with a qualified reference from `_macro_support` to avoid name clashes. I ran into the same issue as this https://github.com/tokio-rs/tracing/issues/3023 with the `line!` macro.
I went ahead and used a qualified path for any references to `core` and `std` out of an abundance of caution since some people do have crates named `core` (https://github.com/tokio-rs/tracing/issues/2761).
=> Qualify all references in macros to avoid name clashes

Cargo.lock, insta/Cargo.toml, insta/src/settings.rs
This gets rid of the only proc macro dependency of insta. Both pin-project and pin-project-lite are maintained by the same person.
=> Switch from pin-project to pin-project-lite

Cargo.lock, insta/Cargo.toml, insta/src/settings.rs
Reverts #711 and #737.
It's for a singular unsafe on a rather uncommon path, that is not worth pulling dependencies in.
=> Remove pin-project dependencies

Cargo.lock, insta/Cargo.toml, insta/src/content/yaml/vendored/hashmap.rs, insta/src/content/yaml/vendored/mod.rs, insta/src/content/yaml/vendored/yaml.rs
For the limited uses of what insta has, there is not a lot of code needed.  This comes at the cost of storing keys twice, but I believe that this is somewhat acceptable for the uses here.  It would also be possible to replace this entirely with a `Vec<(Yaml, Yaml)>` with a further refactor since the yaml structure isn't really used other than to convert to `Content` in most places.  That does not apply to tests and a handful other places.
Fixes #740
=> Replace linked-hash-map with a basic hashmap wrapper

insta/src/env.rs
The existing test expects to be in a path that ends with `insta`. In a git worktree that's often not the case.
I think this change may make the test a bit impotent, but it does fix the issue, and I don't think the test is _that_ important. (other ideas welcome as ever)
=> Fix test when not in `insta` path

CHANGELOG.md, cargo-insta/src/cli.rs, cargo-insta/src/container.rs, insta/src/env.rs
This implements uppercase keyboard shortcuts for bulk operations in
the snapshot review interface:
- 'A' to accept all remaining snapshots
- 'R' to reject all remaining snapshots
- 'S' to skip all remaining snapshots
(for transparency, claude code helped a lot with this)
=> Add uppercase keyboard shortcuts for bulk actions in cargo insta review

Cargo.lock, cargo-insta/Cargo.toml
This fixes parsing of `+ use<'a>` syntax.
"syn" claims to support rustc 1.61, so I think it's compatible with MSRV of cargo-insta.
=> Bump syn to latest version 2.0.100

.typos.toml
excludes a current error from `pre-commit`
=> add config for typos

.pre-commit-config.yaml
=> use fixed tag for `typos`

cargo-insta/tests/functional/inline.rs, cargo-insta/tests/functional/workspace.rs, insta/src/content/json.rs, insta/src/serialization.rs, insta/src/snapshot.rs, insta/src/utils.rs, insta/tests/snapshots/test_redaction__foo_bar.snap, insta/tests/snapshots/test_redaction__foo_bar_alt.snap, insta/tests/snapshots/test_redaction__foo_bar_deep.snap, insta/tests/snapshots/test_redaction__foo_bar_full_range.snap, insta/tests/snapshots/test_redaction__foo_bar_range.snap, insta/tests/snapshots/test_redaction__foo_bar_range_from.snap, insta/tests/snapshots/test_redaction__foo_bar_range_to.snap, insta/tests/snapshots/test_redaction__rounded_redaction.snap, insta/tests/snapshots/test_redaction__user_json.snap, insta/tests/snapshots/test_redaction__user_json_flags.snap, insta/tests/snapshots/test_redaction__user_json_flags_alt.snap, insta/tests/snapshots/test_redaction__user_json_settings.snap, insta/tests/snapshots/test_redaction__user_json_settings_callback.snap, insta/tests/snapshots/test_redaction__with_random_value.snap, insta/tests/snapshots/test_redaction__with_random_value_and_match_comma-2.snap, insta/tests/snapshots/test_redaction__with_random_value_and_match_comma.snap, insta/tests/snapshots/test_redaction__with_random_value_and_trailing_comma.snap, insta/tests/snapshots/test_redaction__with_random_value_inline_callback.snap, insta/tests/snapshots/test_redaction__with_random_value_json_match.snap, insta/tests/snapshots/test_redaction__with_random_value_json_settings2.snap, insta/tests/test_basic.rs, insta/tests/test_inline.rs, insta/tests/test_redaction.rs, insta/tests/test_settings.rs
As well as isolating future diffs to changes that matter, helps identify a couple of issues; e.g. how the turbofish is formatted in the `Selector` expressions
=> Run with `--force-update-snapshots`
