- src/runtime.rs
> Fix windows build

- cargo-insta/src/cargo.rs
- cargo-insta/src/cli.rs
This in theory lets someone use this with non rust projects as a review tool.
> Added support for non cargo based invokation

- cargo-insta/src/cargo.rs
- src/runtime.rs
- tests/test_inline.rs
As discussed in https://github.com/mitsuhiko/insta/issues/39
> Handle new line characters as final characters

- cargo-insta/src/inline.rs
- tests/test_inline.rs
> Columns are actually utf-8 byte offsets instead of char offsets

- src/runtime.rs
This adds line numbers to the diff view that show the old and new lines similar
to how this would look like in a real diffing tool.
> Added better line numbers to diffs

- cargo-insta/src/cargo.rs
> Imply --all for workspaces without root crate

- cargo-insta/src/cli.rs
This rejects old snapshots before the test run which prevents the creation of
false positives.  This can be disabled by a flag.
This also adds a quiet mode to reject/accept.
> Reject snapshots before test run

- src/macros.rs
- src/runtime.rs
I was trying to do something more ambitious; in the meantime this is a small saving
> ReferenceValue only borrows, no need for Cow

- src/lib.rs
- src/redaction.rs
- src/runtime.rs
- src/settings.rs
- tests/test_redaction.rs
This improves the dynamic redaction system by exposing a better API.
> Improve exposed dynamic redactions

- README.md
- src/lib.rs
- src/runtime.rs
Lets you remove the diff from the output.
Fixes #99
> Added output control to insta

- cargo-insta/src/cli.rs
This fixes some small annoyances with the CLI. It honors `INSTA_UPDATE` now somewhat so if someone tries to use it, it does not silently corrupt. It also now gives a hint if someone runs `cargo insta test` without `review`.
This refs #100
> Small improvements to the CLI

- src/redaction.rs
- tests/test_redaction.rs
> Added support for newtype variant redactions.

- Cargo.toml
- cargo-insta/Cargo.lock
- src/runtime.rs
> Kill difference.rs for similar

- src/runtime.rs
- tests/test_clash_detection.rs
> Detect a case of snapshot name clashes

- CHANGELOG.md
- src/content.rs
- src/lib.rs
- src/redaction.rs
- src/settings.rs
- tests/snapshots/test_redaction__user_json_flags.snap
- tests/snapshots/test_redaction__user_json_flags_alt.snap
- tests/test_redaction.rs
This should make it possible to force a set to be sorted.
Fixes #211.
> Added support for a sorting redaction

- CHANGELOG.md
- src/macros.rs
- tests/test_settings.rs
This is the behavior one would actually expect.
> Inherit settings in with_settings!

- src/content/json.rs
As part of the 0.18 upgrade non string keys were accidentally not supported.
Fixes #280
> Add support for numeric keys to JSON

- cargo-insta/src/cli.rs
- src/env.rs
- src/lib.rs
> Add cargo-insta test behavior flags to tool config

- src/env.rs
This was incorrectly picked up from the wrong place.
Refs #329
> Fix incorrect mapping of review.include_ignored

- cargo-insta/src/cargo.rs
> Fix non working include-hidden flag

- .github/workflows/tests.yml
- cargo-insta/src/cli.rs
> Added --exclude to cargo insta test

- CHANGELOG.md
- cargo-insta/src/cli.rs
> Inherit color behavior from CARGO_TERM_COLOR env var

- cargo-insta/src/cli.rs
See
https://github.com/rust-lang/cargo/blob/5bf83d8146f1c674dc874ad20ab209490aec6422/tests/testsuite/cargo_test/help/stdout.log#L40.
> cargo-insta: support --all-targets

- .github/workflows/tests.yml
> .github: add rust cache

- CHANGELOG.md
- cargo-insta/src/cli.rs
- cargo-insta/src/walk.rs
> Added multi --package support

- CHANGELOG.md
- src/env.rs
> Fix a crash with a file called .config

- cargo-insta/src/cli.rs
- src/env.rs
- src/lib.rs
- src/runtime.rs
- src/snapshot.rs
May need some refining. 
Closes https://github.com/mitsuhiko/insta/issues/351, but with an additional option, since `force_update` seems like a bad term for this
Is this reasonable in principle?
> Add `require_full_match` option

- src/macros.rs
- src/snapshot.rs
Fixes the issue at the bottom of https://github.com/mitsuhiko/insta/pull/385#issuecomment-1975321767. 
Sorry for the mistake. 
I've added a test, which fails prior to the change.
~(FWIW I may have spotted a different bug re snapshots not updating after the first failure, I'm investigating...)~ Couldn't reproduce, don't think it's a thing.
> Fix ownership issue

- tests/snapshots/test_inline__unnamed_single_line-2.snap
- tests/snapshots/test_inline__unnamed_single_line.snap
- tests/test_inline.rs
Maybe not worth a PR, but not sure what these tests were doing in `test_inline.rs`. (I added them five years ago!)
> Remove unused tests

- .pre-commit-config.yaml
- CHANGELOG.md
- insta/src/content/yaml/vendored/emitter.rs
- insta/src/env.rs
- insta/src/macros.rs
- insta/src/settings.rs
...which fixes a bunch of typos automatically
> Add pre-commit / typos

- .github/workflows/tests.yml
- insta/src/macros.rs
Assert no warnings (will fail at first)
> Test `cargo doc` in CI

- CHANGELOG.md
- cargo-insta/src/cli.rs
> Only pass --color if not always to work around custom runners

- insta/src/runtime.rs
I got confused at https://github.com/mitsuhiko/insta/pull/489/files#r1640317409
> Add docstring for `ReferenceValue`

- CHANGELOG.md
- cargo-insta/src/cli.rs
> cargo-insta: allow multiple --exclude flags

- insta/src/snapshot.rs
I was confused understanding this code; added some comments and a debug assertion; hope that's reasonable.
> Add debug assertion & comments

- .vscode/settings.json
Existing settings' keys have been renamed
> Update VS Code settings

- cargo-insta/tests/main.rs
This adds the tests from #532 into the repo so we can compare the changes between existing `master` and the new code in that PR.
One test panics, which is tagged with a `#[should_panic]` here (and we will remove the attribute in #532)
> Add test showing panic from nested crate

- cargo-insta/tests/main.rs
This wasn't working, so I wrote a test. Then I realized I had `cargo-insta` 1.39 installed. But the test remains useful.
> Add integration test for multiple `#`

- insta/src/snapshot.rs
Small changes to make this test easier to read
> Make `test_normalize_inline_snapshot` easier to read

- cargo-insta/src/inline.rs
Was trying to work out whether it extracted hashes, got a useful test as a side-effect
> Add test for `find_snapshot_macro`

- cargo-insta/src/walk.rs
> Small refactor & docstring of some code in walk.rs

- cargo-insta/tests/main.rs
- insta/src/serialization.rs
Moving some unambiguous code from #563 into a new PR so we can keep moving
> Add integration test for old inline format

- insta/src/snapshot.rs
Now that some PRs have merged, this cleans up a couple functions
> Small refactor of inline normalization

- CHANGELOG.md
- cargo-insta/tests/main.rs
- insta/src/snapshot.rs
My previous implementation added them too liberally
> Only add `#` characters when required

- cargo-insta/src/walk.rs
- insta/src/runtime.rs
Spotted when reviewing code; this uses native rust methods rather than specific slicing
> Couple of small refinements to prefix / suffixes

- insta/src/env.rs
- insta/src/runtime.rs
As I'm trying to understand parts of the code
> Add a couple comments

- cargo-insta/src/cli.rs
- cargo-insta/src/utils.rs
- insta/src/content/yaml/vendored/emitter.rs
- insta/src/glob.rs
- insta/src/lib.rs
- insta/src/settings.rs
During https://github.com/mitsuhiko/insta/pull/618 I noticed few missing quotes here and there and a minor gramar issue which bugged me ^^
(separate PR for reviewability)
> docs: improved monospace quoting and gramar fixes

- insta/src/content/mod.rs
- insta/src/snapshot.rs
> Improve error message on file write error

- CONTRIBUTING.md
I realize this was quite helpful for me, took me a while to figure it out.
Also some general spring-cleaning
> Update `CONTRIBUTING.md` with running working version of `cargo-insta`

- CONTRIBUTING.md
Small fix of a sentence I just added
> Refine grammar

- cargo-insta/src/cli.rs
- cargo-insta/src/container.rs
- cargo-insta/src/inline.rs
- cargo-insta/src/walk.rs
- cargo-insta/tests/main.rs
> Fix & test the check for hidden / ignored snapshots

- cargo-insta/src/cli.rs
- cargo-insta/tests/functional/workspace.rs
This wasn't working, I think because of my recent changes -- now fixed and tested
> Fix passing `--workspace-root` to `cargo-insta`

- cargo-insta/tests/functional/main.rs
Needed for a different branch, committing this change to `main`
> Show hidden files in functional tests

- cargo-insta/src/cli.rs
- cargo-insta/src/utils.rs
- insta/src/env.rs
- insta/src/lib.rs
- insta/src/utils.rs
Still a bit of a mess, but marginally better
> Small simplification of `prepare_test_runner`

- CHANGELOG.md
> Fix command in changelog

- CHANGELOG.md
> Add changelog for INSTA_WORKSPACE_ROOT at compile time

- cargo-insta/src/cargo.rs
- cargo-insta/tests/functional/main.rs
- cargo-insta/tests/functional/workspace.rs
> Fix duplicate snapshots on multiple targets with identical roots

- insta/src/snapshot.rs
slightly cleaner and faster (no clone), and no panics
> Minor optimization of required hashes

- Cargo.toml
not sure why this isn't working, trying something before spending more time debugging
> Update runners for `dist` on musl

- CHANGELOG.md
- Cargo.lock
- insta/Cargo.toml
- insta/src/snapshot.rs
> chore: bump libc crate
